# zshenv file for server


### PATHS ###

export PATH="${PATH}:${HOME}/.local/bin:/opt/bin:/usr/sbin/"
export NODE_PATH="/usr/local/lib/node:/usr/local/lib/node_modules"

### LOAD RVM IF AVAILABLE ###
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
