"$schema" = 'https://starship.rs/config-schema.json'

[battery]
disabled = true

[directory]
truncate_to_repo = false

[golang]
symbol = " "

[java]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[shell]
disabled = false
nu_indicator = "nsh"
unknown_indicator = "sh?"
format = "[$indicator]($style)"
