#!/bin/bash

layout() {
  setxkbmap -query | grep layout | awk '{print $2}'
}

variant() {
  setxkbmap -query | grep variant | awk '{print $2}' | head -c 2
}

case $BLOCK_BUTTON in
  1) # toggle between dvorak and qwerty
    if [ "$(variant)" == "dv" ]; then
      setxkbmap us
    else
      setxkbmap us dvorak
    fi
    ;;
esac

VARIANT="$(variant)"
LAYOUT="$(layout)"

echo "${VARIANT:-$LAYOUT}"
