#!/bin/bash

SINK="${BLOCK_INSTANCE:-$(pactl list sinks short | grep RUNNING | awk '{print $1}')}"

# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="${1:-5%}"

#------------------------------------------------------------------------

volume() {
  pactl list sinks | \
    grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | \
    sed -e 's/.* \([0-9][0-9]*\)%.*/\1/'
}

muted() {
  pactl list sinks | \
    grep '^[[:space:]]Mute:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | \
    awk '{print $2}'
}

case $BLOCK_BUTTON in
  3) pactl set-sink-mute $SINK toggle ;;  # right click, mute/unmute
  4) pactl set-sink-volume $SINK +$STEP ;; # scroll up, increase
  5) pactl set-sink-volume $SINK -$STEP ;; # scroll down, decrease
esac

if [ "$(muted)" = "yes" ]; then
  echo "muted ($(volume)%)"
  echo "mute"
  echo \#B58900
else
  echo "$(volume)%"
fi
