theme = "solarized_dark"

[editor]
auto-format = false
rulers = [80, 92, 100, 120]
color-modes = true
scrolloff = 1
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "file-name",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "separator",
  "file-type",
  "position-percentage",
  "position",
  "file-encoding",
]

[editor.statusline.mode]
normal = "N"
insert = "I"
select = "S"

[editor.whitespace.render]
space = "none"
nbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "␣"
tab = "»"
tabpad = " "

[editor.indent-guides]
render = true
