[[language]]
name = "php"
indent = { tab-width = 2, unit = "\t" }
language-servers = [
	{ name = "intelephense" }
]

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "\t" }

[language-servers.intelephense]
command = "intelephense"
args = ["--stdio"]
config = { licenseKey = "{{intelephense_license_key}}" }

[langauge-servers.rust-analyzer]
command = "rust-analyzer"
