return {
	{
		'simrat39/symbols-outline.nvim',
		maps = {
			{ '<Leader>o', '<Cmd>SymbolsOutline<CR>', desc = 'Open outline' },
		},
		opts = {
			auto_preview = false,
			symbols = {
				File = { icon = 'file' },
				Module = { icon = 'mod' },
				Namespace = { icon = '∷' },
				Package = { icon = 'pkg' },
				Class = { icon = 'Ϲ' },
				Method = { icon = 'µ' },
				Property = { icon = '+' },
				Field = { icon = '-' },
				Constructor = { icon = '¢' },
				Enum = { icon = 'Ε' },
				Interface = { icon = 'Ι' },
				Function = { icon = 'ƒ' },
				Variable = { icon = 'ν' },
				Constant = { icon = 'π' },
				String = { icon = '$' },
				Number = { icon = '#' },
				Boolean = { icon = '!' },
				Array = { icon = '@' },
				Object = { icon = '⊙' },
				Key = { icon = 'κ' },
				Null = { icon = '∅' },
				EnumMember = { icon = '·' },
				Struct = { icon = '§' },
				Event = { icon = '&' },
				Operator = { icon = '⊕' },
				TypeParameter = { icon = 'Τ' },
			},
		},
	},
}
