#!/bin/sh

# ticketnumber=$(git branch | grep ^* | sed -E 's/\* tickets\/([a-z0-9]+)-.*/\1/g')
# re='^[0-9]+$'
# if ! [[ $ticketnumber =~ $re ]] ; then
# 	exit
# fi
# 
# originalmessage=`cat $1`
# 
# sed -ie '1s/$/\
# \
# https:\/\/bugs.citd.tamu.edu\/show_bug.cgi?id='"$ticketnumber/" "$1"
