# zshenv for imac.local


### PATHS ###

export PATH="/usr/local/bin:/usr/local/mysql/bin:${PATH}:${HOME}/Library/Scripts:/usr/local/share/npm/bin"
# export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:/usr/local/mysql/lib"
export NODE_PATH="/usr/local/lib/node:/usr/local/lib/node_modules"


### ENVIRONMENT VARIABLES AND OPTIONS ###

export COPYFILE_DISABLE=true
