# zshenv for matthew-macbook


### PATHS ###
export PATH="/usr/local/share/npm/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/local/sbin:$PATH:$HOME/Library/Scripts"
# export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/mysql/lib"
export NODE_PATH="/usr/local/lib/node_modules:/usr/local/share/npm/lib/node_modules"

### ENVIRONMENT VARS AND OPTIONS ###
export COPYFILE_DISABLE=true
