# zshrc file for matthew-macbook.local


### OH-MY-ZSH ###

plugins=("${plugins[@]}"
    brew
    git-flow
    osx
    rbenv
    sublime
    terminalapp
)


### ALIASES ###

# open folder in Finder
alias finder='open -a Finder'

# Soundboard
alias sb='${HOME}/Music/soundboard/soundboard'

# One Vim ... just one (http://www.derekwyatt.org/vim/vim-tutorial-videos/vim-intermediate-tutorial-videos/#onevim)
alias m='mvim --remote-silent'

# Sage
alias sage='/opt/sage/sage'

# Todo.txt
alias t='todo.sh'


### RBENV INIT ###
eval "$(rbenv init -)"
