# zshrc for server


### OH-MY-ZSH ###

plugins=("${plugins[@]}"
    debian
    git-flow
)


### VARIABLES AND OPTIONS ###

ZSH_TMUX_AUTOSTART="true"


# colorized diff
# if [[ -n `which colordiff` ]]; then
#     function diff() { diff $@ | colordiff }
#     function gdiff() { gdiff $@ | colordiff }
#     function sdiff() { svn diff $@ | colordiff }
# fi


### ALIASES ###

# CLI Dropbox status
#alias dst="$HOME/bin/dropbox status"
#alias dfst="$HOME/bin/dropbox filestatus"

alias svc="sudo service"
alias msm="sudo /etc/init.d/msm"
alias t="todo.sh"
alias hb="HandBrakeCLI"
