# update script {{{

[updater.files]
"update.sh" = "~/.local/bin/update.sh"

# }}}

# operating systems {{{

# linux {{{

# arch {{{

[archlinux]
depends = ["pacman"]

[archlinux-fish]
depends = ["archlinux", "fish"]

[archlinux-fish.files]
"archlinux/fish_command_not_found.fish" = "~/.config/fish/functions/fish_command_not_found.fish"

# }}}
# debian {{{

[debian]
depends = ["apt"]

# }}}
# ubuntu {{{

[ubuntu]
depends = ["debian"]

# }}}

# }}}

# }}}

# apt {{{

[apt]
depends = ["updater"]

[apt.files]
"apt/update.sh" = "~/.config/update.d/10-apt.sh"

# }}}
# bash {{{

[bash.files]
"bash/rc.d" = "~/.config/bash/rc.d"
"bash/bash_logout" = "~/.bash_logout"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"

# }}}
# direnv {{{

[direnv-bash]
depends = ["bash"]

[direnv-bash.files]
"direnv/init.bash" = "~/.config/bash/rc.d/50-direnv.sh"

[direnv-fish]
depends = ["fish"]

[direnv-fish.files]
"direnv/init.fish" = "~/.config/fish/conf.d/direnv.fish"

# }}}
# fish {{{

[fish]
depends = ["updater"]

[fish.files]
"fish/config" = "~/.config/fish"
"fish/update.fish" = "~/.config/update.d/50-fish.fish"

# }}}
# flatpak {{{

[flatpak]
depends = ["updater"]

[flatpak.files]
"flatpak/update.sh" = "~/.config/update.d/20-flatpak.sh"

# }}}
# gem {{{

[gem.files]
"gem/gemrc" = "~/.gemrc"

[gem-zsh]
depends = ["zsh"]

[gem-zsh.files]
"gem/init.zsh" = "~/.zsh/env.d/gem.zsh"

# }}}
# git {{{

[git.files]
"git/config" = "~/.gitconfig"
"git/ignore" = "~/.config/git/ignore"

# }}}
# mpv {{{

[mpv.files]
mpv = "~/.config/mpv"

# }}}
# n {{{

[n]
depends = ["updater"]

[n.files]
"n/update.sh" = "~/.config/update.d/50-n.sh"

# }}}
# npm {{{

[npm]
depends = ["updater"]

[npm.files]
"npm/update.sh" = "~/.config/update.d/50-npm-global.sh"

# }}}
# nvim {{{

[nvim]
depends = ["updater"]

[nvim.files]
"nvim/config" = "~/.config/nvim"
"nvim/update.sh" = "~/.config/update.d/50-neovim.sh"

# }}}
# pacman {{{

[pacman]
depends = ["updater"]

[pacman.files]
"pacman/makepkg.conf" = "~/.config/pacman/makepkg.conf"
"pacman/update.sh" = "~/.config/update.d/10-pacman.sh"
"pacman/update-aur.sh" = "~/.config/update.d/15-aur.sh"

# }}}
# php-dev {{{

[php-dev-fish]
depends = ["fish"]

[php-dev-fish.files]
"php-dev/fish" = "~/.config/fish"

[php-dev-zsh]
depends = ["zsh"]

[php-dev-zsh.files]
"php-dev/zsh" = "~/.zsh"

# }}}
# pyv {{{

[pyv-fish]
depends = ["fish"]

[pyv-fish.files]
"pyv/fish" = "~/.config/fish"

[pyv-zsh]
depends = ["zsh"]

[pyv-zsh.files]
"pyv/zsh" = "~/.zsh"

# }}}
# rbenv {{{

[rbenv]
depends = ["updater"]

[rbenv.files]
"rbenv/update.sh" = "~/.config/update.d/50-rbenv.sh"

[rbenv-bash]
depends = ["bash", "rbenv"]

[rbenv-bash.files]
"rbenv/init.bash" = "~/.config/bash/rc.d/50-rbenv.sh"

[rbenv-fish]
depends = ["fish", "rbenv"]

[rbenv-fish.files]
"rbenv/init.fish" = "~/.config/fish/conf.d/10-rbenv.fish"

[rbenv-zsh]
depends = ["rbenv", "zsh"]

[rbenv-zsh.files]
"rbenv/init.zsh" = "~/.zsh/plugins.d/rbenv.zsh"

# }}}
# rustup {{{

[rustup]
depends = ["updater"]

[rustup.files]
"rustup/update.sh" = "~/.config/update.d/50-rustup.sh"

# }}}
# ssh {{{

[ssh.files]
"ssh/config" = "~/.ssh/config"

# }}}
# tmux {{{

[tmux.files]
"tmux/tmux.conf" = "~/.tmux.conf"

# }}}
# vscode {{{

[vscode-fish]
depends = ["fish"]

[vscode-fish.files]
"vscode/shell-integration.fish" = "~/.config/fish/conf.d/10-vscode.fish"

# }}}
# watson {{{

[watson.files]
"watson/config" = "~/.config/watson/config"

[watson-fish]
depends = ["fish", "watson"]

[watson-fish.files]
"watson/fish" = "~/.config/fish"

[watson-zsh]
depends = ["watson", "zsh"]

[watson-zsh.files]
"watson/zsh" = "~/.zsh"

# }}}
# zsh {{{

[zsh]
depends = ["updater"]

[zsh.files]
"zsh/antigenrc" = "~/.zsh/antigenrc"
"zsh/plugins" = "~/.zsh/plugins"
"zsh/themes" = "~/.zsh/themes"
"zsh/update.zsh" = "~/.config/update.d/50-zsh.zsh"
"zsh/zlogin" = "~/.zlogin"
"zsh/zlogout" = "~/.zlogout"
"zsh/zprofile" = "~/.zprofile"
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.zshrc"

# }}}

# vim: foldmethod=marker
