# bash {{{

[bash.files]
"bash/rc.d" = "~/.config/bash/rc.d"
"bash/bash_logout" = "~/.bash_logout"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"

# }}}
# fish {{{

[fish.files]
"fish/config" = "~/.config/fish"
"fish/update.fish" = "~/.config/update.d/50-fish.fish"

# }}}
# flatpak {{{

[flatpak.files]
"flatpak/update.sh" = "~/.config/update.d/20-flatpak.sh"

# }}}
# nvim {{{

[nvim.files]
"nvim/config" = "~/.config/nvim"
"nvim/update.sh" = "~/.config/update.d/50-neovim.sh"

# }}}

# vim: foldmethod=marker
