# global defaults {{{

[default.variables]
grammarly_client_id = ""
intelephense_license_key = ""
editor = "vim"

# }}}
# {{{ global updater and config loader priorities
#
# 10 - distro system package managers
#
# - apt
# - homebrew
# - pacman
#
# 15 third-party system package managers and software sources
#
# - aur
# - nix
#
# 20 - system containerized app managers
#
# - flatpak
# - snap
#
# 30 - user environment config
#
# - aliases (loading)
# - dotfiles
#
# 40 - runtime version managers
#
# - mise
# - n
# - rbenv
#
# 50 - user package managers
#
# - npm-global
#
# 60 - shell plugins
#
# - fish
# - zsh
# - starship (update)
#
# 80 - misc software and plugins
#
# - rustup
# - tt
# - vim
# - ytdl
#
# 90 - late-binding shell environment
#
# - fzf (loading)
# - starship (loading)
# - zoxide (loading)
#
# }}}

# update script {{{

[updater.files]
"update.sh" = "~/.local/bin/update.sh"
"pull-and-deploy.sh" = "~/.config/update.d/30-dotfiles.sh"

# }}}

# base operating systems {{{

# linux {{{

# arch {{{

[archlinux]
depends = ["pacman"]

[archlinux.files]
"archlinux/fish_command_not_found.fish" = { target = "~/.config/fish/functions/fish_command_not_found.fish", type = "symbolic", if = "dotter.packages.fish" }

# }}}
# debian {{{

[debian]
depends = ["apt"]

# }}}
# ubuntu {{{

[ubuntu]
depends = ["debian"]

# }}}

# }}}
# macos {{{

[macos]
depends = ["homebrew"]

[macos.files]
"macos/env.zsh" = { target = "~/.zsh/env.d/macos.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}

# }}}

# shells {{{

# bash {{{

[bash.files]
"bash/env.d" = "~/.config/bash/env.d"
"bash/rc.d" = "~/.config/bash/rc.d"
"bash/bash_logout" = "~/.bash_logout"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"

# }}}
# fish {{{

[fish]
depends = ["updater"]

[fish.files]
"fish/config" = "~/.config/fish"
"fish/update.fish" = "~/.config/update.d/60-fish.fish"

# vanilla prompt {{{

[fish-prompt]
depends = ["fish"]

[fish-prompt.files]
"fish/prompt" = "~/.config/fish/functions"

# }}}

# }}}
# nushell {{{

[nushell.files]
"nushell" = "~/.config/nushell"

# }}}
# zsh {{{

[zsh]
depends = ["updater"]

[zsh.files]
"zsh/antidoterc" = "~/.zsh/antidoterc"
"zsh/plugins" = "~/.zsh/plugins"
#"zsh/themes" = "~/.zsh/themes"
"zsh/update.zsh" = "~/.config/update.d/60-zsh.zsh"
"zsh/zlogin" = "~/.zlogin"
"zsh/zlogout" = "~/.zlogout"
"zsh/zprofile" = "~/.zprofile"
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.zshrc"

# }}}

# }}}
# package managers {{{

# apt {{{

[apt]
depends = ["updater"]

[apt.files]
"apt/update.sh" = "~/.config/update.d/10-apt.sh"

# }}}
# flatpak {{{

[flatpak]
depends = ["updater"]

[flatpak.files]
"flatpak/update.sh" = "~/.config/update.d/20-flatpak.sh"

# }}}
# homebrew {{{

[homebrew]
depends = ["updater"]

[homebrew.files]
"homebrew/update.sh" = "~/.config/update.d/10-homebrew.sh"
"homebrew/init.bash" = { target = "~/.config/bash/env.d/10-homebrew.sh", type = "template", if = "dotter.packages.bash" }
"homebrew/init.fish" = { target = "~/.config/fish/conf.d/10-homebrew.fish", type = "template", if = "dotter.packages.fish" }
"homebrew/init.nu" = { target = "~/.local/share/nushell/vendor/autoload/10-homebrew.nu", type = "template", if = "dotter.packages.nushell" }
"homebrew/init.zsh" = { target = "~/.zsh/env.d/10-homebrew.zsh", type = "template", if = "dotter.packages.zsh" }

# }}}
# nix {{{

[nix]
depends = ["updater"]

[nix.files]
"nix/nix.conf" = "~/.config/nix/nix.conf"
"nix/update.sh" = "~/.config/update.d/15-nix.sh"

# }}}
# pacman {{{

[pacman]
depends = ["updater"]

[pacman.files]
"pacman/makepkg.conf" = "~/.config/pacman/makepkg.conf"
"pacman/update.sh" = "~/.config/update.d/10-pacman.sh"
"pacman/update-aur.sh" = "~/.config/update.d/15-aur.sh"

# }}}
# snap {{{

[snap]
depends = ["updater"]

[snap.files]
"snap/update.sh" = "~/.config/update.d/20-snap.sh"

# }}}

# }}}

# aliases {{{

[aliases.files]
"aliases/aliases.bash" = { target = "~/.config/bash/rc.d/30-aliases.sh", type = "symbolic", if = "dotter.packages.bash" }
"aliases/aliases.fish" = { target = "~/.config/fish/conf.d/30-aliases.fish", type = "symbolic", if = "dotter.packages.fish" }
"aliases/aliases.nu" = { target = "~/.local/share/nushell/vendor/autoload/30-aliases.nu", type = "symbolic", if = "dotter.packages.nushell" }
"aliases/aliases.zsh" = { target = "~/.zsh/rc.d/30-aliases.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# atuin {{{

[atuin.files]
"atuin/config.toml" = "~/.config/atuin/config.toml"
"atuin/init.bash" = { target = "~/.config/bash/rc.d/90-atuin.sh", type = "symbolic", if = "dotter.packages.bash" }
"atuin/init.fish" = { target = "~/.config/fish/conf.d/90-atuin.fish", type = "symbolic", if = "dotter.packages.fish" }
"atuin/init.zsh" = { target = "~/.zsh/rc.d/90-atuin.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# btop / bpytop {{{

[btop.files]
btop = "~/.config/btop"

[bpytop.files]
btop = "~/.config/bpytop"

# }}}
# direnv {{{

[direnv.files]
"direnv/config.toml" = "~/.config/direnv/config.toml"
"direnv/init.bash" = { target = "~/.config/bash/rc.d/50-direnv.sh", type = "symbolic", if = "dotter.packages.bash" }
"direnv/init.fish" = { target = "~/.config/fish/conf.d/direnv.fish", type = "symbolic", if = "dotter.packages.fish" }
"direnv/plugin.zsh" = { target = "~/.zsh/plugins.d/direnv.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# dolpinsay {{{

[dolphinsay.files]
"dolphinsay/art" = { target = "~/.config/dolphinsay/art", type = "symbolic" }
"dolphinsay/dolphinsay.sh" = "~/.local/bin/dolphinsay"


[dolphinsay-greet]
depends = ["dolphinsay"]

[dolphinsay-greet.files]
"dolphinsay/text/clothing" = { target = "~/.config/dolphinsay/text/clothing", type = "symbolic" }
"dolphinsay/text/sayings" = { target = "~/.config/dolphinsay/text/sayings", type = "symbolic" }
"dolphinsay/greeting.sh" = { target = "~/.config/bash/rc.d/99-dolphinsay-greet.sh", type = "symbolic", if = "dotter.packages.bash" }
"dolphinsay/fish_greeting.fish" = { target = "~/.config/fish/functions/fish_greeting.fish", type = "symbolic", if = "dotter.packages.fish" }
"dolphinsay/greeting.sh" = { target = "~/.zsh/rc.d/99-dolphinsay-greet.zsh", type = "symbolic", if = "dotter.packages.zsh" }

[dolphinsay-greet-nsfw.files]
"dolphinsay/text/nsfw" = { target = "~/.config/dolphinsay/text/nsfw", type = "symbolic" }

# }}}
# duplicity {{{

[duplicity.files]
"duplicity" = "~/.config/systemd/user"

[duplicity.variables]
duplicity_target_url = "sftp://matthew@nymbus.home.komputerwiz.net//mnt/zfs/orca/files/backup/%H/duplicity/%i"

# }}}
# fzf {{{

[fzf.files]
"fzf/init.bash" = { target = "~/.config/bash/rc.d/90-fzf.sh", type = "symbolic", if = "dotter.packages.bash" }
"fzf/init.fish" = { target = "~/.config/fish/conf.d/90-fzf.fish", type = "symbolic", if = "dotter.packages.fish" }
"fzf/init.zsh" = { target = "~/.zsh/rc.d/90-fzf.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# gem {{{

[gem.files]
"gem/gemrc" = "~/.gemrc"
"gem/init.zsh" = { target = "~/.zsh/env.d/gem.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# ghostty {{{

[ghostty.files]
"ghostty" = "~/.config/ghostty"

[ghostty.variables]
ghostty_font_size = 12

# }}}
# git {{{

[git.files]
"git/config" = "~/.gitconfig"
"git/ignore" = "~/.config/git/ignore"

[git.variables]
email = "komputerwiz.matt@gmail.com"

# }}}
# helix {{{

[helix.files]
"helix" = { target = "~/.config/helix", type = "symbolic" }

# }}}
# hyprland {{{

[hyprland.files]
"hyprland/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"hyprland/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
"hyprland/dunstrc" = "~/.config/dunst/dunstrc"
"hyprland/waybar" = "~/.config/waybar"
"hyprland/wofi" = "~/.config/wofi"

# }}}
# KDE / plasma {{{

[kde-plasma.files]
"kde-plasma/wallpapers" = "~/.local/share/wallpapers"

# }}}
# latex {{{

[latex.files]
"latex/packages" = { target = "~/texmf/tex/latex", type = "symbolic" }

# }}}
# mise-en-place {{{

[mise]
depends = ["updater"]

[mise.files]
"mise-en-place/config.toml" = "~/.config/mise/config.toml"
"mise-en-place/update.sh" = "~/.config/update.d/40-mise.sh"
"mise-en-place/init.bash" = { target = "~/.config/bash/rc.d/40-mise.sh", type = "symbolic", if = "dotter.packages.bash" }
"mise-en-place/init.fish" = { target = "~/.config/fish/conf.d/40-mise.fish", type = "symbolic", if = "dotter.packages.fish" }
"mise-en-place/init.zsh" = { target = "~/.zsh/rc.d/40-mise.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# mpv {{{

[mpv.files]
mpv = "~/.config/mpv"

# }}}
# n {{{

[n]
depends = ["updater"]

[n.files]
"n/update.sh" = "~/.config/update.d/40-n.sh"
"n/env.bash" = { target = "~/.config/bash/env.d/40-n.sh", type = "template", if = "dotter.packages.bash" }
"n/env.zsh" = { target = "~/.zsh/env.d/40-n.zsh", type = "template", if = "dotter.packages.zsh" }

[n.variables]
n_prefix = "$HOME/.local/opt/n"

# }}}
# neovide {{{

[neovide]
depends = ["nvim"]

[neovide.files]
"nvim/neovide/config.toml" = "~/.config/neovide/config.toml"

# }}}
# npm {{{

[npm]
depends = ["updater"]

[npm.files]
"npm/update.sh" = "~/.config/update.d/50-npm-global.sh"

# }}}
# nvim {{{

[nvim.files]
"nvim/config" = { target = "~/.config/nvim", type = "symbolic" }
"nvim/system.vim" = "~/.config/nvim/plugin/system.vim"

[nvim.variables]
nvim_python3 = "/usr/bin/python3"
nvim_ruby = "/usr/bin/neovim-ruby-host"
nvim_shell = "/bin/bash"

# }}}
# php-dev {{{

[php-dev.files]
"php-dev/fish" = { target = "~/.config/fish", type = "symbolic", if = "dotter.packages.fish" }
"php-dev/zsh" = { target = "~/.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# pyv {{{

[pyv.files]
"pyv/fish" = { target = "~/.config/fish", type = "symbolic", if = "dotter.packages.fish" }
"pyv/zsh" = { target = "~/.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# rbenv {{{

[rbenv]
depends = ["updater"]

[rbenv.files]
"rbenv/update.sh" = "~/.config/update.d/40-rbenv.sh"
"rbenv/env.bash" = { target = "~/.config/bash/env.d/40-rbenv.sh", type = "template", if = "dotter.packages.bash" }
"rbenv/init.bash" = { target = "~/.config/bash/rc.d/40-rbenv.sh", type = "symbolic", if = "dotter.packages.bash" }
"rbenv/init.fish" = { target = "~/.config/fish/conf.d/40-rbenv.fish", type = "symbolic", if = "dotter.packages.fish" }
"rbenv/init.zsh" = { target = "~/.zsh/plugins.d/rbenv.zsh", type = "symbolic", if = "dotter.packages.zsh" }

[rbenv.variables]
rbenv_root = "$HOME/.local/opt/rbenv"

# }}}
# rustup {{{

[rustup]
depends = ["updater"]

[rustup.files]
"rustup/update.sh" = "~/.config/update.d/80-rustup.sh"
"rustup/env.bash" = { target = "~/.config/bash/env.d/80-rustup.sh", type = "template", if = "dotter.packages.bash" }
"rustup/env.zsh" = { target = "~/.zsh/env.d/80-rustup.zsh", type = "template", if = "dotter.packages.zsh" }

[rustup.variables]
rustup_home = "$HOME/.local/opt/rustup"
cargo_home = "$HOME/.local/opt/cargo"

# }}}
# ssh {{{

[ssh.files]
"ssh/config" = "~/.ssh/config"

# }}}
# starship {{{

[starship.files]
"starship/config.toml" = "~/.config/starship.toml"
"starship/init.bash" = { target = "~/.config/bash/rc.d/90-starship.sh", type = "symbolic", if = "dotter.packages.bash" }
"starship/init.fish" = { target = "~/.config/fish/conf.d/90-starship.fish", type = "symbolic", if = "dotter.packages.fish" }
"starship/init.zsh" = { target = "~/.zsh/rc.d/90-starship.zsh", type = "symbolic", if = "dotter.packages.zsh" }

[starship-updater]
depends = ["starship", "updater"]

[starship-updater.files]
"starship/install-or-update.sh" = "~/.config/update.d/60-starship.sh"

# }}}
# tailscale {{{

[tailscale.files]
"tailscale/ts" = "~/.local/bin/ts"

# }}}
# tmux {{{

[tmux.files]
"tmux/tmux.conf" = "~/.tmux.conf"

# }}}
# trash {{{

[trash-macos.files]
"trash/macos/rm.fish" = { target = "~/.config/fish/functions/rm.fish", type = "symbolic", if = "dotter.packages.fish" }

# }}}
# tt (time-tracker) {{{

[tt.files]
"tt/config.toml" = "~/.config/tt/config.toml"
"tt/init.bash" = { target = "~/.config/bash/rc.d/80-tt.sh", type = "symbolic", if = "dotter.packages.bash" }
"tt/init.fish" = { target = "~/.config/fish/conf.d/80-tt.fish", type = "symbolic", if = "dotter.packages.fish" }
"tt/init.zsh" = { target = "~/.zsh/rc.d/80-tt.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# vim {{{

[vim]
depends = ["updater"]

[vim.files]
"vim/update.sh" = "~/.config/update.d/80-vim.sh"
"vim/runtime" = { target = "~/.vim", type = "symbolic" }
"vim/vimrc" = { target = "~/.vimrc", type = "symbolic" }

# }}}
# vscode {{{

[vscode.files]
"vscode/shell-integration.fish" = { target = "~/.config/fish/conf.d/10-vscode.fish", type = "symbolic", if = "dotter.packages.fish" }

# }}}
# watson {{{

[watson.files]
"watson/config" = "~/.config/watson/config"
"watson/fish" = { target = "~/.config/fish", type = "symbolic", if = "dotter.packages.fish" }
"watson/zsh" = { target = "~/.zsh", type = "symbolic", if = "dotter.packages.zsh" }

# }}}
# ytdl {{{

[ytdl.files]
"ytdl/fish" = { target = "~/.config/fish", type = "symbolic", if = "dotter.packages.fish" }

[ytdl-updater]
depends = ["updater", "ytdl"]

[ytdl-updater.files]
"ytdl/update.sh" = "~/.config/update.d/80-ytdl.sh"

# }}}
# zoxide {{{

[zoxide.files]
"zoxide/init.bash" = { target = "~/.config/bash/rc.d/90-zoxide.sh", type = "template", if = "dotter.packages.bash" }
"zoxide/init.fish" = { target = "~/.config/fish/conf.d/90-zoxide.fish", type = "template", if = "dotter.packages.fish" }
"zoxide/plugin.zsh" = { target = "~/.zsh/plugins.d/zoxide.zsh", type = "template", if = "dotter.packages.zsh" }

[zoxide.variables]
zoxide_command = "z"

#}}}

# vim: foldmethod=marker foldlevel=0
