# update script {{{

[updater.files]
"update.sh" = "~/.local/bin/update.sh"

# }}}
# bash {{{

[bash.files]
"bash/rc.d" = "~/.config/bash/rc.d"
"bash/bash_logout" = "~/.bash_logout"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"

# }}}
# direnv {{{

[direnv-bash.files]
"direnv/init.bash" = "~/.config/bash/rc.d/50-direnv.sh"

[direnv-fish.files]
"direnv/init.fish" = "~/.config/fish/conf.d/direnv.fish"

# }}}
# fish {{{

[fish]
depends = ["updater"]

[fish.files]
"fish/config" = "~/.config/fish"
"fish/update.fish" = "~/.config/update.d/50-fish.fish"

# }}}
# flatpak {{{

[flatpak]
depends = ["updater"]

[flatpak.files]
"flatpak/update.sh" = "~/.config/update.d/20-flatpak.sh"

# }}}
# git {{{

[git.files]
"git/config" = "~/.gitconfig"
"git/ignore" = "~/.config/git/ignore"

# }}}
# nvim {{{

[nvim]
depends = ["updater"]

[nvim.files]
"nvim/config" = "~/.config/nvim"
"nvim/update.sh" = "~/.config/update.d/50-neovim.sh"

# }}}

# vim: foldmethod=marker
