# update script {{{

[updater.files]
"update.sh" = "~/.local/bin/update.sh"
"pull-and-deploy.sh" = "~/.config/update.d/45-dotfiles.sh"

# }}}

# operating systems {{{

# linux {{{

# arch {{{

[archlinux]
depends = ["pacman"]

[archlinux-fish]
depends = ["archlinux", "fish"]

[archlinux-fish.files]
"archlinux/fish_command_not_found.fish" = "~/.config/fish/functions/fish_command_not_found.fish"

# }}}
# debian {{{

[debian]
depends = ["apt"]

# }}}
# ubuntu {{{

[ubuntu]
depends = ["debian"]

# }}}

# }}}
# macos {{{

[macos]
depends = ["homebrew"]

[macos-zsh]
depends = ["macos", "zsh"]

[macos-zsh.files]
"macos/env.zsh" = "~/.zsh/env.d/macos.zsh"

# }}}

# }}}

# apt {{{

[apt]
depends = ["updater"]

[apt.files]
"apt/update.sh" = "~/.config/update.d/10-apt.sh"

# }}}
# bash {{{

[bash.files]
"bash/env.d" = "~/.config/bash/env.d"
"bash/rc.d" = "~/.config/bash/rc.d"
"bash/bash_logout" = "~/.bash_logout"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"

[bash.variables]
editor = "vim"

# }}}
# direnv {{{

[direnv.files]
"direnv/config.toml" = "~/.config/direnv/config.toml"

[direnv-bash]
depends = ["bash", "direnv"]

[direnv-bash.files]
"direnv/init.bash" = "~/.config/bash/rc.d/50-direnv.sh"

[direnv-fish]
depends = ["direnv", "fish"]

[direnv-fish.files]
"direnv/init.fish" = "~/.config/fish/conf.d/direnv.fish"

[direnv-zsh]
depends = ["direnv", "zsh"]

[direnv-zsh.files]
"direnv/plugin.zsh" = "~/.zsh/plugins.d/direnv.zsh"

# }}}
# duplicity {{{

[duplicity.files]
"duplicity" = "~/.config/systemd/user"

[duplicity.variables]
duplicity_gpg_passphrase = "***REMOVED***"
duplicity_target_url = "sftp://matthew@nymbus.home.komputerwiz.net//mnt/zfs/orca/files/backup/%H/duplicity/%i"

# }}}
# fish {{{

[fish]
depends = ["updater"]

[fish.files]
"fish/config" = "~/.config/fish"
"fish/update.fish" = "~/.config/update.d/50-fish.fish"

# vanilla prompt {{{

[fish-prompt]
depends = ["fish"]

[fish-prompt.files]
"fish/prompt" = "~/.config/fish/functions"

# }}}

# }}}
# flatpak {{{

[flatpak]
depends = ["updater"]

[flatpak.files]
"flatpak/update.sh" = "~/.config/update.d/20-flatpak.sh"

# }}}
# gem {{{

[gem.files]
"gem/gemrc" = "~/.gemrc"

[gem-zsh]
depends = ["zsh"]

[gem-zsh.files]
"gem/init.zsh" = "~/.zsh/env.d/gem.zsh"

# }}}
# git {{{

[git.files]
"git/config" = "~/.gitconfig"
"git/ignore" = "~/.config/git/ignore"

[git.variables]
email = "komputerwiz.matt@gmail.com"

# }}}
# helix {{{

[helix.files]
"helix" = "~/.config/helix"

# }}}
# homebrew {{{

[homebrew]
depends = ["updater"]

[homebrew.files]
"homebrew/update.sh" = "~/.config/update.d/10-homebrew.sh"

[homebrew-bash]
depends = ["homebrew", "bash"]

[homebrew-bash.files]
"homebrew/init.bash" = "~/.config/bash/env.d/10-homebrew.sh"

[homebrew-fish]
depends = ["homebrew", "fish"]

[homebrew-fish.files]
"homebrew/init.fish" = "~/.config/fish/conf.d/10-homebrew.fish"

# }}}
# latex {{{

[latex.files]
"latex/packages" = { target = "~/texmf/tex/latex", type = "symbolic" }

# }}}
# mpv {{{

[mpv.files]
mpv = "~/.config/mpv"

# }}}
# n {{{

[n]
depends = ["updater"]

[n.files]
"n/update.sh" = "~/.config/update.d/50-n.sh"

[n-bash]
depends = ["bash", "n"]

[n-bash.files]
"n/env.bash" = "~/.config/bash/env.d/50-n.sh"

[n-bash.variables]
n_prefix = "$HOME/.local/opt/n"

# }}}
# nix {{{

[nix.files]
"nix" = "~/.config/nix"

# }}}
# npm {{{

[npm]
depends = ["updater"]

[npm.files]
"npm/update.sh" = "~/.config/update.d/50-npm-global.sh"

# }}}
# nushell {{{

[nushell.files]
"nushell" = "~/.config/nushell"

# }}}
# nvim {{{

[nvim]
depends = ["updater"]

[nvim.files]
"nvim/config" = { target = "~/.config/nvim", type = "symbolic" }
"nvim/update.sh" = "~/.config/update.d/50-nvim.sh"
"nvim/system.vim" = "~/.config/nvim/plugin/system.vim"

[nvim.variables]
nvim_python3 = "/usr/bin/python3"
nvim_ruby = "/usr/bin/neovim-ruby-host"
nvim_shell = "/bin/bash"

# }}}
# pacman {{{

[pacman]
depends = ["updater"]

[pacman.files]
"pacman/makepkg.conf" = "~/.config/pacman/makepkg.conf"
"pacman/update.sh" = "~/.config/update.d/10-pacman.sh"
"pacman/update-aur.sh" = "~/.config/update.d/15-aur.sh"

# }}}
# php-dev {{{

[php-dev-fish]
depends = ["fish"]

[php-dev-fish.files]
"php-dev/fish" = "~/.config/fish"

[php-dev-zsh]
depends = ["zsh"]

[php-dev-zsh.files]
"php-dev/zsh" = "~/.zsh"

# }}}
# pyv {{{

[pyv-fish]
depends = ["fish"]

[pyv-fish.files]
"pyv/fish" = "~/.config/fish"

[pyv-zsh]
depends = ["zsh"]

[pyv-zsh.files]
"pyv/zsh" = "~/.zsh"

# }}}
# rbenv {{{

[rbenv]
depends = ["updater"]

[rbenv.files]
"rbenv/update.sh" = "~/.config/update.d/50-rbenv.sh"

[rbenv-bash]
depends = ["bash", "rbenv"]

[rbenv-bash.files]
"rbenv/env.bash" = "~/.config/bash/env.d/50-rbenv.sh"
"rbenv/init.bash" = "~/.config/bash/rc.d/50-rbenv.sh"

[rbenv-bash.variables]
rbenv_root = "$HOME/.local/opt/rbenv"

[rbenv-fish]
depends = ["fish", "rbenv"]

[rbenv-fish.files]
"rbenv/init.fish" = "~/.config/fish/conf.d/10-rbenv.fish"

[rbenv-zsh]
depends = ["rbenv", "zsh"]

[rbenv-zsh.files]
"rbenv/init.zsh" = "~/.zsh/plugins.d/rbenv.zsh"

# }}}
# rustup {{{

[rustup]
depends = ["updater"]

[rustup.files]
"rustup/update.sh" = "~/.config/update.d/50-rustup.sh"

[rustup-bash]
depends = ["bash", "rustup"]

[rustup-bash.files]
"rustup/env.bash" = "~/.config/bash/env.d/50-rustup.sh"

[rustup-bash.variables]
rustup_home = "$HOME/.local/opt/rustup"
cargo_home = "$HOME/.local/opt/cargo"

# }}}
# snap {{{

[snap]
depends = ["updater"]

[snap.files]
"snap/update.sh" = "~/.config/update.d/20-snap.sh"

# }}}
# ssh {{{

[ssh.files]
"ssh/config" = "~/.ssh/config"

# }}}
# starship {{{

[starship.files]
"starship/config.toml" = "~/.config/starship.toml"

[starship-updater]
depends = ["starship", "updater"]

[starship-updater.files]
"starship/install-or-update.sh" = "~/.config/update.d/50-starship.sh"

[starship-bash]
depends = ["bash", "starship"]

[starship-bash.files]
"starship/init.bash" = "~/.config/bash/rc.d/90-starship.sh"

[starship-fish]
depends = ["fish", "starship"]

[starship-fish.files]
"starship/init.fish" = "~/.config/fish/conf.d/90-starship.fish"

[starship-zsh]
depends = ["starship", "zsh"]

[starship-zsh.files]
"starship/init.zsh" = "~/.zsh/rc.d/90-starship.zsh"

# }}}
# tmux {{{

[tmux.files]
"tmux/tmux.conf" = "~/.tmux.conf"

# }}}
# vim {{{

[vim]
depends = ["updater"]

[vim.files]
"vim/update.sh" = "~/.config/update.d/50-vim.sh"
"vim/runtime" = { target = "~/.vim", type = "symbolic" }
"vim/vimrc" = { target = "~/.vimrc", type = "symbolic" }

# }}}
# vscode {{{

[vscode-fish]
depends = ["fish"]

[vscode-fish.files]
"vscode/shell-integration.fish" = "~/.config/fish/conf.d/10-vscode.fish"

# }}}
# watson {{{

[watson.files]
"watson/config" = "~/.config/watson/config"

[watson-fish]
depends = ["fish", "watson"]

[watson-fish.files]
"watson/fish" = "~/.config/fish"

[watson-zsh]
depends = ["watson", "zsh"]

[watson-zsh.files]
"watson/zsh" = "~/.zsh"

# }}}
# ytdl {{{

[ytdl]

[ytdl-updater]
depends = ["updater", "ytdl"]

[ytdl-updater.files]
"ytdl/update.sh" = "~/.config/update.d/50-ytdl.sh"


[ytdl-fish]
depends = ["fish", "ytdl"]

[ytdl-fish.files]
"ytdl/fish" = "~/.config/fish"


# }}}
# zoxide {{{

[zoxide.variables]
zoxide_command = "z"

[zoxide-bash]
depends = ["bash", "zoxide"]

[zoxide-bash.files]
"zoxide/init.bash" = "~/.config/bash/rc.d/90-zoxide.sh"

[zoxide-fish]
depends = ["fish", "zoxide"]

[zoxide-fish.files]
"zoxide/init.fish" = "~/.config/fish/conf.d/90-zoxide.fish"

[zoxide-zsh]
depends = ["zoxide", "zsh"]

[zoxide-zsh.files]
"zoxide/plugin.zsh" = "~/.zsh/plugins.d/zoxide.zsh"

#}}}
# zsh {{{

[zsh]
depends = ["updater"]

[zsh.files]
"zsh/antigenrc" = "~/.zsh/antigenrc"
"zsh/plugins" = "~/.zsh/plugins"
#"zsh/themes" = "~/.zsh/themes"
"zsh/update.zsh" = "~/.config/update.d/50-zsh.zsh"
"zsh/zlogin" = "~/.zlogin"
"zsh/zlogout" = "~/.zlogout"
"zsh/zprofile" = "~/.zprofile"
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.zshrc"

# }}}

# vim: foldmethod=marker
