# update script {{{

[updater.files]
"update.sh" = "~/.local/bin/update.sh"

# }}}
# bash {{{

[bash.files]
"bash/rc.d" = "~/.config/bash/rc.d"
"bash/bash_logout" = "~/.bash_logout"
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.profile"

# }}}
# direnv {{{

[direnv-bash]
depends = ["bash"]

[direnv-bash.files]
"direnv/init.bash" = "~/.config/bash/rc.d/50-direnv.sh"

[direnv-fish]
depends = ["fish"]

[direnv-fish.files]
"direnv/init.fish" = "~/.config/fish/conf.d/direnv.fish"

# }}}
# fish {{{

[fish]
depends = ["updater"]

[fish.files]
"fish/config" = "~/.config/fish"
"fish/update.fish" = "~/.config/update.d/50-fish.fish"

# }}}
# flatpak {{{

[flatpak]
depends = ["updater"]

[flatpak.files]
"flatpak/update.sh" = "~/.config/update.d/20-flatpak.sh"

# }}}
# git {{{

[git.files]
"git/config" = "~/.gitconfig"
"git/ignore" = "~/.config/git/ignore"

# }}}
# n {{{

[n]
depends = ["updater"]

[n.files]
"n/update.sh" = "~/.config/update.d/50-n.sh"

# }}}
# npm {{{

[npm]
depends = ["updater"]

[npm.files]
"npm/update.sh" = "~/.config/update.d/50-npm-global.sh"

# }}}
# nvim {{{

[nvim]
depends = ["updater"]

[nvim.files]
"nvim/config" = "~/.config/nvim"
"nvim/update.sh" = "~/.config/update.d/50-neovim.sh"

# }}}
# php-dev {{{

[php-dev-fish]
depends = ["fish"]

[php-dev-fish.files]
"php-dev/fish" = "~/.config/fish"

[php-dev-zsh]
depends = ["zsh"]

[php-dev-zsh.files]
"php-dev/zsh" = "~/.zsh"

# }}}
# pyv {{{

[pyv-fish]
depends = ["fish"]

[pyv-fish.files]
"pyv/fish" = "~/.config/fish"

[pyv-zsh]
depends = ["zsh"]

[pyv-zsh.files]
"pyv/zsh" = "~/.zsh"

# }}}

# vim: foldmethod=marker
