# .zshenv
# This file is loaded unconditionally:
# -> /etc/zshenv    +  ~/.zshenv
#    /etc/zprofile  +  ~/.zprofile
#    /etc/zshrc     +  ~/.zshrc
#    /etc/zlogin    +  ~/.zlogin
#    ...
#    /etc/zlogout   +  ~/.zlogout


### ENVIRONMENT VARIABLES AND OPTIONS ###

# my files are not writable
umask 022

# other environment variables
export EDITOR="{{editor}}"

# set antigen install path
export ADOTDIR="$HOME/.zsh/antigen"


### GLOBAL PATHS ###

[ -d "$HOME/.local/bin" ] && export PATH="$PATH:$HOME/.local/bin"


### LOAD ADDITIONAL LOCAL FILES ###

for file in "$HOME"/.zsh/env.d/*.zsh(N); do source "$file"; done
