# .zshrc
# This file is loaded only if the shell is an interactive shell:
#    /etc/zshenv    +  ~/.zshenv
#    /etc/zprofile  +  ~/.zprofile
# -> /etc/zshrc     +  ~/.zshrc
#    /etc/zlogin    +  ~/.zlogin
#    ...
#    /etc/zlogout   +  ~/.zlogout


### ANTIGEN ###

source "$ADOTDIR/antigen.zsh"
antigen init "$HOME/.zsh/antigenrc"


### OPTIONS ###

# don't bug me about filename expansion
setopt no_nomatch
# immediately execute history line
setopt no_hist_verify
# do not beep for autocomplete
setopt no_list_beep
# oh yeah!
setopt dvorak
# extra goodies for file globbing (like *~*.js)
setopt extended_glob


### KEY BINDINGS ###

zmodload zsh/terminfo

# common terminal keybindings
bindkey "$terminfo[khome]" beginning-of-line
bindkey "$terminfo[kend]" end-of-line
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
bindkey "$terminfo[kdch1]" delete-char-or-list


# fix issue with vi-mode and history-substring-search
# see https://github.com/robbyrussell/oh-my-zsh/issues/2735

# bind k and j for VI mode
#bindkey -M vicmd 'k' history-substring-search-up
#bindkey -M vicmd 'j' history-substring-search-down

# bind UP and DOWN arrow keys
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down
bindkey "$terminfo[cuu]" history-substring-search-up
bindkey "$terminfo[cud]" history-substring-search-down
bindkey "\e[A" history-substring-search-up
bindkey "\e[B" history-substring-search-down

# autosuggest
bindkey '^ ' autosuggest-accept


### ALIASES ###

alias t='todo.sh'
alias v="$EDITOR"

# list files
alias la='ls -a'
alias ll='ls -hl'
alias lal='ls -ahl'
alias lla='ls -ahl'
alias l='ls -F'

# ask for confirmation on copy and move
#alias cp='cp -i'
#alias mv='mv -i'

# git shorthand
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gbd='git branch --delete'
alias gbl='git blame -b -w -C -C -C'
alias gbs='git bisect'
alias gbsb='git bisect bad'
alias gbsg='git bisect good'
alias gbsr='git bisect reset'
alias gbss='git bisect start'
alias gc='git commit -v'
#alias gc!='git commit -v --amend'
alias gca='git commit -v --amend'
#alias gcn!='git commit -v --no-edit --amend'
alias gcan='git commit -v --amend --no-edit'
#alias gcb='git checkout -b'
#alias gcm='git checkout master'
#alias gco='git checkout'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gd='git diff'
alias gdca='git diff --cached'
alias gdt='git difftool'
alias gf='git fetch'
alias gfa='git fetch --all --prune --jobs=10'
alias gg='git log --pretty=oneline-detailed --graph --all --decorate --date=iso'
alias gl='git pull'
alias gls='git log --stat'
alias glsp='git log --stat -p'
alias gm='git merge'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gp='git push'
#alias gp!='git push --force'
alias gpf='git push --force-with-lease'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase --interactive'
#alias grbm='git rebase master'
alias grbs='git rebase --skip'
alias grm='git rm'
alias grmc='git rm --cached'
alias grs='git restore --staged'
#alias gsm='git submodule'
alias gst='git status'
alias gsta='git stash push'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'
alias gsw='git switch'
alias gswc='git switch --create'
alias gy='git apply'
alias gyr='git apply --reverse'

# canonical mode for viewing binary files
alias hexdump='hexdump -C'
alias od='od -Ax -tx1'


### FUNCTIONS ###

# aggressive garbage collection on a git repo
git-gc-aggressive () {
    rm -rf .git/refs/original/*
    git reflog expire --all --expire-unreachable=0
    git repack -A -d
    git prune
}

# system-independent way of copying stdin to the clipboard
__copy_to_clipboard() {
    if [ "$(uname)" == "Darwin" ]; then
        pbcopy
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        if [ -z "$(which xsel)" ]; then
          xsel -b
        elif [ -z "$(which xclip)" ]; then
          xclip -selection CLIPBOARD
        else
          echo "Unable to copy to clipboard: xsel nor xclip is installed." >&2
          cat
        fi
    else
        cat
    fi
}

# perform a hash of the string in the given argument and copy it to the clipboard
copy_hash() {
    echo -n "$2" | openssl dgst "-$1" | cut -d ' ' -f 2 | awk '{printf("%s",$0);}' | __copy_to_clipboard
}

# Perform a given command in each git repository in the current directory.
each_repo() {
    ROOT_PWD="$(pwd)"
    for REPO in $(ls); do
        # skip if not a directory or a git repository
        if [[ ! ( -d "$REPO"  && -d "$REPO/.git" ) ]]; then
            continue
        fi
        cd "$REPO"
        echo "\n$REPO"
        if eval "$@"; then
            # command succeeded
        else
            echo -e "\e31mfailure to execute in $REPO"
        fi
        cd "$ROOT_PWD"
    done
}


### AUTOSUGGESTIONS CONFIG ###

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)


### LOAD ADDITIONAL LOCAL FILES ###

for file in "$HOME"/.zsh/rc.d/*.zsh(N); do source "$file"; done
