# zshrc for <del>simlab-barry</del> <del><ins>tcat-mbarry</ins><del> <ins>mbarry</ins>

### OH-MY-ZSH ###
plugins=("${plugins[@]}"
    git-flow
    # rbenv
)


st_run() { nohup /usr/bin/subl $@ > /dev/null & }
alias st=st_run
alias stt='st .'

alias ff='$(thefuck $(fc -ln -1))'

alias mvn='mvn -Dtycho.localArtifacts=ignore'

# use extended regex by default
alias sed='sed -r'

### SOURCE HIGHLIGHTING IN LESS ###
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '


### FUNCTION each_repo ###
# Perform a given command in each git repository in the current directory.

each_repo() {
    ROOT_PWD="$(pwd)"
    for REPO in $(ls); do
        # skip if not a directory or a git repository
        if [[ ! ( -d "$REPO"  && -d "$REPO/.git" ) ]]; then
            continue
        fi
        cd "$REPO"
        echo "$REPO"
        eval $@
        cd "$ROOT_PWD"
    done
}
